Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from policyengine_us.model_api import *


class ignore_reported(Reform):
    def apply(self):
        self.neutralize_variable("spm_unit_net_income_reported")


class neutralize_cdcc(Reform):
    def apply(self):
        self.neutralize_variable("cdcc")


sim = Microsimulation(ignore_reported, year=2020)
sim_no_cdcc = Microsimulation((ignore_reported, neutralize_cdcc), year=2020)

(
    sim.calc("spm_unit_net_income", period=2022).sum()
    - sim_no_cdcc.calc("spm_unit_net_income", period=2022).sum()
) / 1e6
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 14[0m
[1;32m     10[0m     [38;5;28;01mdef[39;00m [38;5;21mapply[39m([38;5;28mself[39m):
[1;32m     11[0m         [38;5;28mself[39m[38;5;241m.[39mneutralize_variable([38;5;124m"[39m[38;5;124mcdcc[39m[38;5;124m"[39m)
[0;32m---> 14[0m sim [38;5;241m=[39m [43mMicrosimulation[49m[43m([49m[43mignore_reported[49m[43m,[49m[43m [49m[43myear[49m[38;5;241;43m=[39;49m[38;5;241;43m2020[39;49m[43m)[49m
[1;32m     15[0m sim_no_cdcc [38;5;241m=[39m Microsimulation((ignore_reported, neutralize_cdcc), year[38;5;241m=[39m[38;5;241m2020[39m)
[1;32m     17[0m (
[1;32m     18[0m     sim[38;5;241m.[39mcalc([38;5;124m"[39m[38;5;124mspm_unit_net_income[39m[38;5;124m"[39m, period[38;5;241m=[39m[38;5;241m2022[39m)[38;5;241m.[39msum()
[1;32m     19[0m     [38;5;241m-[39m sim_no_cdcc[38;5;241m.[39mcalc([38;5;124m"[39m[38;5;124mspm_unit_net_income[39m[38;5;124m"[39m, period[38;5;241m=[39m[38;5;241m2022[39m)[38;5;241m.[39msum()
[1;32m     20[0m ) [38;5;241m/[39m [38;5;241m1e6[39m

[0;31mTypeError[0m: __init__() got an unexpected keyword argument 'year'
TypeError: __init__() got an unexpected keyword argument 'year'

